### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

### ISSUE THREAD

**Issue by guduxingzou** [jonrein/tensorflow_CTC_example#1]
Traceback (most recent call last):
  File "bdlstm_train_sample.py", line 71, in <module>
    forwardH1 = rnn_cell.LSTMCell(nHidden, use_peepholes=True, state_is_tuple=True)
TypeError: **init**() got an unexpected keyword argument 'state_is_tuple'

> > > tensorflow.**version**
> > > '0.8.0'

**Comment by jonrein** [comment]
Example code assumes tensorflow version 0.9.0.  If updating is problematic, try omitting the "state_is_tuple" argument.  Running with that set to True in v0.9 speeds up the calculation relative to 0.8, but shouldn't change the output (I think).

**Comment by guduxingzou** [comment]
I omitt the "state_is_tuple" ，then it is running.thanks!
