### ISSUE TITLE
label error rate or label correct rate ?

### ISSUE THREAD

**Issue by anxingle** [jonrein/tensorflow_CTC_example#4]
I wonder [errorRate](https://github.com/jonrein/tensorflow_CTC_example/blob/master/bdlstm_train_sample.py#L88) should be correct rate,so it just be clerical error or something else?   When terminal print :**Epoch , 230, 'error rate:'  0.90**  .  It means  model  predict correctly  about  90%  or 10% ?  
Thank you .

**Comment by bver** [comment]
Levensthein distance of predicted and target outputs is used here, it is indeed an error (smaller is better):
https://www.tensorflow.org/versions/r0.7/api_docs/python/math_ops.html#edit_distance

**Comment by anxingle** [comment]
@bver    Got it . Thanks.

**Comment by anxingle** [comment]
@bver     I wonder the [epochErrorRate:  ](https://github.com/jonrein/tensorflow_CTC_example/blob/master/bdlstm_train_sample.py#L111)  should rewrite to "accuracy rate" .I found that when [errorRate](https://github.com/jonrein/tensorflow_CTC_example/blob/master/bdlstm_train_sample.py#L88) is more  smaller ,the epochErrorRate will be more  bigger.

**Comment by anxingle** [comment]
@bver   I totally misunderstanding it. now, I really got it.
